/**
 * agentic-sdlc-workflow.ts — T22, agentic SDLC plan (tasks/plan.md). The
 * single source `ruflo record workflow-docs` generates CLAUDE.md's,
 * AGENTS.md's, and the Cursor rules file's agentic-sdlc section FROM —
 * "generating all rules files from one source is what prevents the
 * targets from drifting apart" (the task's own rationale). Requirement 1
 * ("any tool") means any AI coding tool with shell access can read this
 * same text and drive the workflow identically; it is deliberately just
 * Markdown, no tool-specific syntax.
 *
 * Scoped narrowly to THIS plan's own workflow (`ruflo record`/`run`), not
 * the separate, pre-existing, general-purpose `@claude-flow/codex`
 * project scaffolder (`CodexInitializer` — bootstraps AGENTS.md/skills/
 * config.toml for an arbitrary NEW project, with zero awareness of this
 * plan). Confirmed with the user before writing anything: extending that
 * generic tool would be a different, much larger task than documenting
 * this one.
 *
 * @module docs/agentic-sdlc-workflow
 */

export const AGENTIC_SDLC_SECTION_START =
  '<!-- AGENTIC-SDLC:START (generated by `ruflo record workflow-docs` — do not hand-edit this section, edit agentic-sdlc-workflow.ts instead) -->';
export const AGENTIC_SDLC_SECTION_END = '<!-- AGENTIC-SDLC:END -->';

export function agenticSdlcWorkflowMarkdown(): string {
  return `## Tool-neutral agentic SDLC (\`ruflo record\` / \`ruflo run\`)

This repo tracks work as typed, git-versioned records under \`docs/{requirements,decisions,tasks}/\`,
validated and advanced through a CLI any AI tool with shell access can drive identically — see
\`tasks/plan.md\` for the full rationale.

### Records and the citation contract

- **requirement** (\`REQ-\`) and **decision** (\`DEC-\`) records: the "why". Each has a
  \`status\`: \`draft\` -> \`accepted\` -> \`superseded\`.
- **task** (\`TASK-\`) records: the "what work". Every task must \`citations:\` at least one
  REQ or DEC — a task with no citation, or one citing only other tasks, is refused at creation.

\`\`\`bash
ruflo record req new --title "..." [--status draft|accepted|superseded]
ruflo record decision new --title "..." [--status draft|accepted|superseded]
ruflo record task new --title "..." --citations REQ-001[,DEC-002] [--priority p0|p1|p2]
ruflo record req|decision|task list
ruflo record req|decision|task show <id>
ruflo record validate            # schema + citation contract + readability + content hash
ruflo record phase-check         # is every task's CURRENT status still earned by its CURRENT fields
\`\`\`

### The task lifecycle

Six states: \`drafted -> specified -> implementing -> verifying -> done\`, and \`blocked\` (never
terminal — always resumable back into the state it failed from). Every forward step needs real
evidence, checked by the SAME code whether a human or an agent drives it:

| Transition | Requires |
|---|---|
| \`drafted -> specified\` | an \`estimate\`, AND every cited REQ/DEC is \`accepted\` (not draft, not superseded) |
| \`specified -> implementing\` | \`doneCriteria\` declared (which test layers apply — an empty list is a valid, deliberate choice) |
| \`implementing -> verifying\` | nothing structural — a human/agent signals readiness; no tool advances this automatically |
| \`verifying -> done\` | the project's own test command exits 0 (never inferred from output text) |

There is no \`--status\` override anywhere in this CLI for an EXISTING task — done is unreachable
except by a real green test result.

\`\`\`bash
ruflo record task verify <id>            # runs the real test command, derives done/blocked
ruflo record task repair <id> [--repair --confirm]   # bounded, budget-capped repair of a red test
ruflo run [--repair --confirm] [--spend-ceiling N]   # advances every task with a real next step,
                                                       # until a full pass makes no more progress
\`\`\`

\`ruflo run\` is restartable — every task file is read fresh and written at most once per pass, so
killing it mid-run and re-invoking is always safe. Repair spends real money only with
\`--confirm\`; without it, it reports the plan and spends nothing.

### The one rule that matters most

If \`ruflo record validate\` and \`ruflo record phase-check\` both pass, the recorded state is
trustworthy — trust the records over any other running summary of what's "done."
`;
}
